version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: antigravity_redis
    ports:
      - "6379:6379"

  api:
    build: ./apps/api       
    container_name: mun_api
    ports:
      - "3000:3000"         
    depends_on:
      - redis              
    environment:
      - REDIS_HOST=${REDIS_HOST}   

  worker:
    build: ./apps/worker
    container_name: mun_worker
    depends_on:
      - redis
      - api 
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - MONGO_URI=${MONGODB_URI}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./apps/worker:/app
